export const ADD_JEWELRY_TO_BASKET = 'ADD_JEWELRY_TO_BASKET';
export const REMOVE_JEWELRY_ITEM = 'REMOVE_JEWELRY_ITEM';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const PLUS_BASKET_ITEM = 'PLUS_BASKET_ITEM';
export const MINUS_BASKET_ITEM = 'MINUS_BASKET_ITEM';
